version: 2
updates:
  # The end of the day anywhere on Earth occurs at 24:00 UTC−12 (`Etc/GMT+12`).
  # Wait for 45 minutes until Dependabot times out in dependency repositories.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '00:45'
      timezone: Etc/GMT-12
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '00:45'
      timezone: Etc/GMT-12
    versioning-strategy: increase
